name:                xin
version:             0.1.0.0
github:              "Verilock-ASPLOS/xin"
license:             BSD3
author:              "Anonymous"
maintainer:          ""
copyright:           ""

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/xin#readme>

dependencies:
- base >= 4.7 && < 5
- text
- directory
- filepath
- template-haskell
- random
- transformers
- containers
- mtl
- lens

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-missing-export-lists

library:
  source-dirs: src

executables:
  xin-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - xin

tests:
  xin-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - xin
